# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21
# Mod Properties
mod_version=1.9.7
maven_group=semmiedev
archives_base_name=disc_jockey
# Dependencies
fabric_api_version=0.161.0+26.3
cloth_config_version=26.3.159
modmenu_version=21.0.0
